Add remote register implementation.
drunomics/contentpool-client pull request #2
Opened 2018-06-26 17:54 UTC by archnode

Fist implementation for automated registration via check.

2018-07-27 12:52 UTC, fago requested changes

2018-07-27 12:52 UTC, fago commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $encoded = \Drupal::service('relaxed.sensitive_data.transformer')->set((string) $uri);
needs to be dependency injected...

2018-07-27 12:52 UTC, fago commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $relaxed_password = \Drupal::service('relaxed.sensitive_data.transformer')->get($relaxed_config->get('password'));
needs to be dependency injected...

2018-07-27 12:52 UTC, fago commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $relaxed_config = \Drupal::config('relaxed.settings');
needs to be dependency injected...

2018-07-27 12:52 UTC, fago commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +   * @param array $configuration
Must have descriptions for every parameter.

2018-07-27 12:52 UTC, fago commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $config = \Drupal::config('system.site');
needs to be dependency injected...
you can use service-utils for many dependencies here - please add it.

2018-07-28 08:11 UTC, archnode commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $encoded = \Drupal::service('relaxed.sensitive_data.transformer')->set((string) $uri);
Already done in other branch

2018-07-28 08:12 UTC, archnode commented on src/Plugin/RemoteCheck/RemoteRegister.php
> +    $relaxed_password = \Drupal::service('relaxed.sensitive_data.transformer')->get($relaxed_config->get('password'));
Already done in other branch

2018-07-31 15:26 UTC, archnode commented
This pr is superseded by #3

2018-07-31 15:26 UTC, closed without merging